api_poskeeper_login:
    path:     /poskeeper-otp-login
    defaults: { _controller: BinduBundle:ApiPoskeeper:login }

api_poskeeper_setup:
    path:     /poskeeper-setup
    defaults: { _controller: BinduBundle:ApiPoskeeper:setup }

api_poskeeper_splash:
    path:     /poskeeper-splash
    defaults: { _controller: BinduBundle:ApiPoskeeper:splash }

api_poskeeper_online_sales_list:
    path:     /poskeeper-online-sales-list
    defaults: { _controller: BinduBundle:ApiPoskeeper:apiOnlineSalesList }

api_poskeeper_online_sales_details:
    path:     /poskeeper-online-sales-details
    defaults: { _controller: BinduBundle:ApiPoskeeper:apiOnlineSalesDetails }

api_poskeeper_app:
    path:     /poskeeper-shop-type
    defaults: { _controller: BinduBundle:ApiPoskeeper:apps }

api_poskeeper_register:
    path:     /poskeeper-store-build
    defaults: { _controller: BinduBundle:ApiPoskeeper:storeBuild }

api_poskeeper_stock_item:
    path:     /poskeeper-stock-item
    defaults: { _controller: BinduBundle:ApiPoskeeper:stockItem }

api_poskeeper_stock_create:
    path:     /poskeeper-stock-create
    defaults: { _controller: BinduBundle:ApiPoskeeper:createStock }
    methods:  POST|GET
    options:
        expose: true

api_poskeeper_stock_edit:
    path:     /poskeeper-stock-edit
    defaults: { _controller: BinduBundle:ApiPoskeeper:stockEdit }

api_poskeeper_stock_update:
    path:     /poskeeper-stock-update
    defaults: { _controller: BinduBundle:ApiPoskeeper:stockUpdate }
    methods:  POST
    options:
        expose: true

api_poskeeper_stock_delete:
    path:     /poskeeper-stock-delete
    defaults: { _controller: BinduBundle:ApiPoskeeper:stockDelete }

api_poskeeper_customer_create:
    path:     /poskeeper-customer-create
    defaults: { _controller: BinduBundle:ApiPoskeeper:createCustomer }
    methods:  POST|GET
    options:
        expose: true

api_poskeeper_customer_update:
    path:     /poskeeper-customer-update
    defaults: { _controller: BinduBundle:ApiPoskeeper:updateCustomer }
    methods:  POST|GET
    options:
        expose: true

api_poskeeper_customer_ledger:
    path:     /poskeeper-customer-ledeger
    defaults: { _controller: BinduBundle:ApiPoskeeper:customerLedger }
    methods:  POST|GET
    options:
        expose: true

api_poskeeper_customer_invoice_details:
    path:     /poskeeper-customer-invoice-details
    defaults: { _controller: BinduBundle:ApiPoskeeper:customerInvoice }
    methods:  POST|GET
    options:
        expose: true

api_poskeeper_sales_payment:
    path:     /poskeeper-payment-receive
    defaults: { _controller: BinduBundle:ApiPoskeeper:salesReceive }
    methods:  POST|GET
    options:
        expose: true

api_poskeeper_vendor_create:
    path:     /poskeeper-vendor-create
    defaults: { _controller: BinduBundle:ApiPoskeeper:createVendor }
    methods:  POST|GET
    options:
        expose: true

api_poskeeper_vendor_update:
    path:     /poskeeper-vendor-update
    defaults: { _controller: BinduBundle:ApiPoskeeper:updateVendor }
    methods:  POST|GET
    options:
        expose: true

api_poskeeper_vendor_ledger:
    path:     /poskeeper-vendor-ledeger
    defaults: { _controller: BinduBundle:ApiPoskeeper:vendorLedger }
    methods:  POST|GET
    options:
        expose: true

api_poskeeper_vendor_invoice_details:
    path:     /poskeeper-vendor-invoice-details
    defaults: { _controller: BinduBundle:ApiPoskeeper:vendorInvoice }
    methods:  POST|GET
    options:
        expose: true

api_poskeeper_vendor_payment:
    path:     /poskeeper-payment
    defaults: { _controller: BinduBundle:ApiPoskeeper:purchasePayment }
    methods:  POST|GET
    options:
        expose: true

api_poskeeper_short_list:
    path:     /poskeeper-purchase-short-list
    defaults: { _controller: BinduBundle:ApiPoskeeper:purchaseShortList }

api_poskeeper_instant_purchase:
    path:     /poskeeper-instant-purchase-item
    defaults: { _controller: BinduBundle:ApiPoskeeper:instantPurchase }

api_poskeeper_add_purchase_shortlist:
    path:     /poskeeper-add-purchase-short-list
    defaults: { _controller: BinduBundle:ApiPoskeeper:insertPurchaseShortItem }


api_poskeeper_sales:
    path:     /poskeeper-sales
    defaults: { _controller: BinduBundle:ApiPoskeeper:apiSales }
    methods:  POST
    options:
        expose: true

api_poskeeper_purchase:
    path:     /poskeeper-purchase
    defaults: { _controller: BinduBundle:ApiPoskeeper:apiPurchase }
    methods:  POST
    options:
        expose: true


api_poskeeper_expense:
    path:     /poskeeper-expense
    defaults: { _controller: BinduBundle:ApiPoskeeper:apiExpense }
    methods:  POST
    options:
        expose: true
