business_stock_transfer:
    path:     /
    defaults: { _controller: "BusinessBundle:StockTransfer:index" }

business_transfer_create:
    path:     /wearhouse-transfer-create
    defaults: { _controller: "BusinessBundle:StockTransfer:create" }
    methods:  [POST]

business_transfer_delete:
    path:     /{id}/particular-delete
    defaults: { _controller: "BusinessBundle:StockTransfer:delete" }
    options:
            expose: true

business_transfer_approve:
    path:     /{id}/particular-approve
    defaults: { _controller: "BusinessBundle:StockTransfer:approved" }
    options:
        expose: true

business_transfer_reverse:
    path:     /{id}/reverse
    defaults: { _controller: "BusinessBundle:StockTransfer:reverse" }
    options:
        expose: true

